// Telas fotografadas para o manual (ambiente de demonstração, banco pei_manual).
// Prefixo do arquivo = capítulo do manual. Ver capturar-telas.mjs para os ajudantes de `acoes`.

export const BASE = 'http://127.0.0.1/fs-v1/public';
export const ADMIN_EMAIL = 'admin.sistema@exemplo.gov.br';
export const USUARIOS = {
  adminUnidade: 'carla.ribeiro@exemplo.gov.br',
  gestor: 'rafael.lima@exemplo.gov.br',
  substituta: 'juliana.costa@exemplo.gov.br',
  consulta: 'paulo.nogueira@exemplo.gov.br',
};

const educativa = 'await expandirEducativa();';
const editarPrimeiro = (padrao, prefixo = 'edit', contem = null) =>
  `const id = idDoPrimeiro(${JSON.stringify(prefixo)}, ${JSON.stringify(contem)}); await chamar(${JSON.stringify(padrao)}, ${JSON.stringify(prefixo)}, id);`;

export const telas = [
  // ── Parte I ────────────────────────────────────────────────────────────
  { arquivo: '02-login.jpg', url: '/login', como: 'visitante' },
  { arquivo: '03-menu.jpg', url: '/dashboard' },
  { arquivo: '03-seletor-unidade.jpg', url: '/dashboard', acoes: `await clicarTexto('Organização Selecionada');` },
  { arquivo: '03-seletor-ciclo.jpg', url: '/dashboard', acoes: `await clicarTexto('Ciclo PEI');` },
  { arquivo: '03-seletor-ano.jpg', url: '/dashboard', acoes: `await clicarTexto('Ano Ref');` },
  { arquivo: '03-sino-alertas.jpg', url: '/dashboard', como: USUARIOS.adminUnidade, acoes: `document.querySelector('button[aria-label^="Notificações"]').click(); await dormir(1200);` },
  { arquivo: '03-sino-atividade.jpg', url: '/dashboard', como: USUARIOS.adminUnidade, acoes: `document.querySelector('button[aria-label^="Notificações"]').click(); await dormir(1000); await clicarTexto('Atividade');` },
  { arquivo: '03-secao-educativa.jpg', url: '/pei/valores', acoes: educativa },
  { arquivo: '04-ajuda-papeis.jpg', url: '/ajuda/papeis' },
  { arquivo: '05-dashboard.jpg', url: '/dashboard' },
  { arquivo: '05-dashboard-graficos.jpg', url: '/dashboard', acoes: `window.scrollTo(0, 900); await dormir(800);` },

  // ── Parte II ───────────────────────────────────────────────────────────
  { arquivo: '06-ciclos.jpg', url: '/pei/ciclos' },
  { arquivo: '06-ciclo-form.jpg', url: '/pei/ciclos', acoes: editarPrimeiro('listar-peis', 'edit', '2024') },
  { arquivo: '06-ciclo-salvar-como.jpg', url: '/pei/ciclos', acoes: `const id = idDoPrimeiro('abrirSalvarComo', '2024'); await chamar('listar-peis','abrirSalvarComo', id);` },
  { arquivo: '06-ciclo-detalhe.jpg', via: { pagina: '/pei/ciclos', href: '/detalhes', contem: '2024' } },
  { arquivo: '07-inaugurar-processo.jpg', url: '/pei/inaugurar' },
  { arquivo: '07-inaugurar-integracao.jpg', url: '/pei/inaugurar', acoes: `await clicarTexto('Integração');` },
  { arquivo: '07-inaugurar-agenda2030.jpg', url: '/pei/inaugurar', acoes: `await clicarTexto('Agenda 2030');` },
  { arquivo: '07-inaugurar-calendario.jpg', url: '/pei/inaugurar', acoes: `await clicarTexto('Calendário');` },

  // ── Parte III ──────────────────────────────────────────────────────────
  { arquivo: '08-cadeia.jpg', url: '/pei/cadeia-valor' },
  { arquivo: '08-cadeia-atividade.jpg', url: '/pei/cadeia-valor', acoes: `const id = idDoPrimeiro('editarAtividade'); await chamar('cadeia-de-valor','editarAtividade', id);` },
  { arquivo: '08-cadeia-processo.jpg', url: '/pei/cadeia-valor', acoes: `const id = idDoPrimeiro('editarProcesso'); await chamar('cadeia-de-valor','editarProcesso', id);` },
  { arquivo: '09-identidade.jpg', url: '/pei' },
  { arquivo: '09-identidade-form.jpg', url: '/pei', acoes: `await chamar('missao-visao','habilitarEdicao');` },
  { arquivo: '09-identidade-detalhe.jpg', via: { pagina: '/pei', href: '/pei/identidade/' } },
  { arquivo: '10-valores.jpg', url: '/pei/valores' },
  { arquivo: '10-valor-form.jpg', url: '/pei/valores', acoes: editarPrimeiro('listar-valores') },
  { arquivo: '10-valor-detalhe.jpg', via: { pagina: '/pei/valores', href: '/pei/valores/' } },
  { arquivo: '11-temas.jpg', url: '/temas-norteadores' },
  { arquivo: '11-tema-form.jpg', url: '/temas-norteadores', acoes: editarPrimeiro('temas-norteadores') },
  { arquivo: '12-pestel.jpg', url: '/pei/pestel' },
  { arquivo: '12-pestel-form.jpg', url: '/pei/pestel', acoes: editarPrimeiro('p-e-s-t-e-l') },
  { arquivo: '13-swot.jpg', url: '/pei/swot' },
  { arquivo: '13-swot-form.jpg', url: '/pei/swot', acoes: editarPrimeiro('s-w-o-t') },
  { arquivo: '13-swot-apresentacao.jpg', url: '/pei/swot', acoes: `await chamar('s-w-o-t','toggleModoVisualizacao');` },
  { arquivo: '13-swot-partes.jpg', url: '/pei/swot', acoes: `rolarAte('Partes Interessadas'); await dormir(600);` },
  { arquivo: '13-swot-cenarios.jpg', url: '/pei/swot', acoes: `rolarAte('Cenários'); await dormir(600);` },
  { arquivo: '13-swot-tows.jpg', url: '/pei/swot', acoes: `rolarAte('TOWS'); await dormir(600);` },
  { arquivo: '14-perspectivas.jpg', url: '/pei/perspectivas' },
  { arquivo: '14-perspectiva-form.jpg', url: '/pei/perspectivas', alto: 1150, acoes: editarPrimeiro('listar-perspectivas') },
  { arquivo: '14-perspectiva-detalhe.jpg', via: { pagina: '/pei/perspectivas', href: '/pei/perspectivas/' } },
  { arquivo: '15-objetivos.jpg', url: '/objetivos' },
  { arquivo: '15-objetivo-form.jpg', url: '/objetivos', alto: 1100, acoes: editarPrimeiro('listar-objetivos') },
  { arquivo: '15-objetivo-detalhe.jpg', via: { pagina: '/objetivos', href: '/objetivos/' } },
  { arquivo: '15-futuro-almejado.jpg', via: [{ pagina: '/objetivos', href: '/detalhes' }, { href: '/futuro' }] },
  { arquivo: '16-mapa.jpg', url: '/pei/mapa', alto: 1700 },
  { arquivo: '16-mapa-individual.jpg', url: '/pei/mapa', alto: 1700, acoes: `await chamar('mapa-estrategico','setViewMode','individual');` },
  { arquivo: '16-mapa-memoria.jpg', url: '/pei/mapa', acoes: `await chamar('mapa-estrategico','abrirMemoriaCalculo', 0);` },
  { arquivo: '17-graus.jpg', url: '/graus-satisfacao' },
  { arquivo: '17-grau-form.jpg', url: '/graus-satisfacao', acoes: editarPrimeiro('graus-satisfacao') },
  { arquivo: '17-grau-detalhe.jpg', via: { pagina: '/graus-satisfacao', href: '/graus-satisfacao/' } },
  { arquivo: '18-agenda2030.jpg', url: '/agenda2030' },
  { arquivo: '18-agenda2030-ods.jpg', url: '/agenda2030', alto: 1100, acoes: `const b = document.querySelector('[wire\\\\:click^="selecionarOds("]'); const n = [...document.querySelectorAll('[wire\\\\:click^="selecionarOds("]')].map(x=>x.getAttribute('wire:click').match(/\\d+/)[0]); await chamar('painel-o-d-s','selecionarOds', 16); rolarAte('ODS 16 ·');` },

  // ── Parte IV ───────────────────────────────────────────────────────────
  { arquivo: '19-indicadores.jpg', url: '/indicadores' },
  { arquivo: '19-indicador-form.jpg', url: '/indicadores', alto: 1100, acoes: editarPrimeiro('listar-indicadores') },
  { arquivo: '19-indicador-metas.jpg', url: '/indicadores', acoes: `const id = idDoPrimeiro('abrirMetas'); await chamar('listar-indicadores','abrirMetas', id);` },
  { arquivo: '19-indicador-linha-base.jpg', url: '/indicadores', acoes: `const id = idDoPrimeiro('abrirLinhaBase'); await chamar('listar-indicadores','abrirLinhaBase', id);` },
  { arquivo: '19-indicador-evolucao.jpg', via: { pagina: '/indicadores', href: '/evolucao' }, alto: 1000 },
  { arquivo: '19-indicador-ficha.jpg', via: { pagina: '/indicadores', href: '/detalhes' }, alto: 1100 },
  { arquivo: '20-iniciativas.jpg', url: '/planos' },
  { arquivo: '20-iniciativa-form.jpg', url: '/planos', alto: 1100, acoes: editarPrimeiro('listar-planos') },
  { arquivo: '20-iniciativa-detalhe.jpg', via: { pagina: '/planos', href: '/detalhes' }, alto: 1100 },
  { arquivo: '20-iniciativa-responsaveis.jpg', via: { pagina: '/planos', href: '/responsaveis' }, alto: 1100 },
  { arquivo: '21-entregas-escolher.jpg', url: '/entregas' },
  { arquivo: '21-entregas-kanban.jpg', via: { pagina: '/entregas', href: '/entregas', contem: 'Portal Único de Serviços' } },
  { arquivo: '21-entregas-lista.jpg', via: { pagina: '/entregas', href: '/entregas', contem: 'Portal Único de Serviços' }, acoes: `await chamar('deliverables','setView','lista');` },
  { arquivo: '21-entregas-calendario.jpg', via: { pagina: '/entregas', href: '/entregas', contem: 'Portal Único de Serviços' }, alto: 1000, acoes: `await chamar('deliverables','setView','calendario');` },
  { arquivo: '21-entregas-timeline.jpg', via: { pagina: '/entregas', href: '/entregas', contem: 'Portal Único de Serviços' }, acoes: `await chamar('deliverables','setView','timeline');` },
  { arquivo: '21-entrega-form.jpg', via: { pagina: '/entregas', href: '/entregas', contem: 'Portal Único de Serviços' }, alto: 1100, acoes: `const id = idDoPrimeiro('openDetails'); await chamar('deliverables','openEditModal', id);` },
  { arquivo: '21-entrega-detalhe.jpg', via: { pagina: '/entregas', href: '/entregas', contem: 'Portal Único de Serviços' }, acoes: `let id = null; for (let i = 0; i < 10 && !id; i++) { id = idDoPrimeiro('openDetails'); if (!id) await dormir(700); } await chamar('deliverables','openDetails', id);` },
  { arquivo: '21-entregas-lixeira.jpg', via: { pagina: '/entregas', href: '/entregas', contem: 'Portal Único de Serviços' }, acoes: `await chamar('deliverables','toggleLixeira');` },
  { arquivo: '22-minhas-entregas.jpg', url: '/minhas-entregas', como: USUARIOS.gestor },
  { arquivo: '23-riscos.jpg', url: '/riscos' },
  { arquivo: '23-risco-form.jpg', url: '/riscos', alto: 1100, acoes: editarPrimeiro('listar-riscos') },
  { arquivo: '23-riscos-matriz.jpg', url: '/riscos/matriz' },
  { arquivo: '23-risco-mitigacao.jpg', via: { pagina: '/riscos', href: '/mitigacao' } },
  { arquivo: '23-risco-ocorrencias.jpg', via: { pagina: '/riscos', href: '/ocorrencias', contem: 'Indisponibilidade prolongada' } },
  { arquivo: '24-rae.jpg', url: '/monitoramento/rae' },
  { arquivo: '24-rae-form.jpg', url: '/monitoramento/rae', alto: 1100, acoes: editarPrimeiro('gerenciar-rae', 'editarRae') },
  { arquivo: '24-rae-encaminhamentos.jpg', url: '/monitoramento/rae', alto: 1300, acoes: `const id = idDoPrimeiro('editarRae'); await chamar('gerenciar-rae','toggleEncaminhamentos', id); rolarAte('Encaminhamentos');` },
  { arquivo: '24-rae-causas.jpg', url: '/monitoramento/rae', alto: 1300, acoes: `const id = idDoPrimeiro('editarRae'); await chamar('gerenciar-rae','toggleCausas', id); rolarAte('Causa');` },
  { arquivo: '25-licoes.jpg', url: '/licoes-aprendidas' },
  { arquivo: '25-licao-form.jpg', url: '/licoes-aprendidas', acoes: editarPrimeiro('licoes-aprendidas', 'editar') },
  { arquivo: '26-relatorios.jpg', url: '/relatorios', alto: 1100 },
  { arquivo: '26-relatorios-historico.jpg', url: '/relatorios/historico' },

  // ── Parte V ────────────────────────────────────────────────────────────
  { arquivo: '27-documentos.jpg', url: '/acervo-documentos' },
  { arquivo: '27-documento-form.jpg', url: '/acervo-documentos', alto: 1000, acoes: editarPrimeiro('listar-documentos') },
  { arquivo: '28-guia-gppei.jpg', url: '/guia-gppei' },
  { arquivo: '29-organizacoes.jpg', url: '/organizacoes' },
  { arquivo: '29-organizacao-form.jpg', url: '/organizacoes', acoes: editarPrimeiro('listar-organizacoes') },
  { arquivo: '29-organizacao-detalhe.jpg', via: { pagina: '/organizacoes', href: '/organizacoes/', contem: 'SPG' } },
  { arquivo: '30-usuarios.jpg', url: '/usuarios' },
  { arquivo: '30-usuario-form.jpg', url: '/usuarios', alto: 1100, acoes: `await chamar('listar-usuarios','create');` },
  { arquivo: '30-usuario-detalhe.jpg', via: { pagina: '/usuarios', href: '/usuarios/' } },
  { arquivo: '31-perfis.jpg', url: '/admin/perfis', alto: 1100 },
  { arquivo: '31-impersonacao.jpg', url: '/dashboard', como: USUARIOS.consulta },
  { arquivo: '32-configuracoes.jpg', url: '/configuracoes' },
  { arquivo: '33-auditoria.jpg', url: '/auditoria' },
  { arquivo: '33-auditoria-detalhe.jpg', via: { pagina: '/auditoria', href: '/auditoria/' } },
  { arquivo: '34-perfil.jpg', url: '/user/profile' },

  // ── Parte VI (sem login) ───────────────────────────────────────────────
  { arquivo: '35-portal-inicio.jpg', url: '/', como: 'visitante' },
  { arquivo: '35-portal-mapa.jpg', url: '/pei/mapa', como: 'visitante', alto: 1100 },
  { arquivo: '35-portal-objetivos.jpg', url: '/objetivos', como: 'visitante' },
  { arquivo: '35-portal-indicadores.jpg', url: '/indicadores', como: 'visitante' },
  { arquivo: '35-portal-iniciativas.jpg', url: '/planos', como: 'visitante' },
];
